const keyboard = [
    {
        id: 1,
        row: 1,
        place: 1,
        en:'`',
        shiftEn:'~',
        ru:'ё',
        shiftRu:'Ё',
    },
    {
        id: 2,
        row: 1,
        place: 2,
        en:'1',
        shiftEn:'!',
        ru:'1',
        shiftRu:'!',
    },
    {
        id: 3,
        row: 1,
        place: 3,
        en:'2',
        shiftEn:'@',
        ru:'2',
        shiftRu:'"',
    },
    {
        id: 4,
        row: 1,
        place: 4,
        en:'3',
        shiftEn:'#',
        ru:'3',
        shiftRu:'№',
    },
    {
        id: 5,
        row: 1,
        place: 5,
        en:'4',
        shiftEn:'$',
        ru:'4',
        shiftRu:';',
    },
    {
        id: 6,
        row: 1,
        place: 6,
        en:'5',
        shiftEn:'%',
        ru:'5',
        shiftRu:'%',
    },
    {
        id: 7,
        row: 1,
        place: 7,
        en:'6',
        shiftEn:'^',
        ru:'6',
        shiftRu:':',
    },
    {
        id: 8,
        row: 1,
        place: 8,
        en:'7',
        shiftEn:'&',
        ru:'7',
        shiftRu:'?',
    },
    {
        id: 9,
        row: 1,
        place: 9,
        en:'8',
        shiftEn:'*',
        ru:'8',
        shiftRu:'*',
    },
    {
        id: 10,
        row: 1,
        place: 10,
        en:'9',
        shiftEn:'(',
        ru:'9',
        shiftRu:'(',
    },
    {
        id: 11,
        row: 1,
        place: 11,
        en:'0',
        shiftEn:')',
        ru:'0',
        shiftRu:')',
    },
    {
        id: 12,
        row: 1,
        place: 12,
        en:'-',
        shiftEn:'_',
        ru:'-',
        shiftRu:'_',
    },
    {
        id: 13,
        row: 1,
        place: 13,
        en:'=',
        shiftEn:'+',
        ru:'=',
        shiftRu:'+',
    },
    {
        id: 14,
        row: 1,
        place: 14,
        en:'Backspace',
        shiftEn:'Backspace',
        ru:'Backspace',
        shiftRu:'Backspace',
    },
    {
        id: 15,
        row: 2,
        place: 1,
        en:'Tab',
        shiftEn:'Tab',
        ru:'Tab',
        shiftRu:'Tab',
    },
    {
        id: 16,
        row: 2,
        place: 2,
        en:'q',
        shiftEn:'Q',
        ru:'й',
        shiftRu:'Й',
    },
    {
        id: 17,
        row: 2,
        place: 3,
        en:'w',
        shiftEn:'W',
        ru:'ц',
        shiftRu:'Ц',
    },
    {
        id: 18,
        row: 2,
        place: 4,
        en:'e',
        shiftEn:'E',
        ru:'у',
        shiftRu:'У',
    },
    {
        id: 19,
        row: 2,
        place: 5,
        en:'r',
        shiftEn:'R',
        ru:'к',
        shiftRu:'К',
    },
    {
        id: 20,
        row: 2,
        place: 6,
        en:'t',
        shiftEn:'T',
        ru:'е',
        shiftRu:'Е',
    },
    {
        id: 21,
        row: 2,
        place: 7,
        en:'y',
        shiftEn:'Y',
        ru:'н',
        shiftRu:'Н',
    },
    {
        id: 22,
        row: 2,
        place: 8,
        en:'u',
        shiftEn:'U',
        ru:'г',
        shiftRu:'Г',
    },
    {
        id: 23,
        row: 2,
        place: 9,
        en:'i',
        shiftEn:'I',
        ru:'ш',
        shiftRu:'Ш',
    },
    {
        id: 24,
        row: 2,
        place: 10,
        en:'o',
        shiftEn:'O',
        ru:'щ',
        shiftRu:'Щ',
    },
    {
        id: 25,
        row: 2,
        place: 11,
        en:'p',
        shiftEn:'P',
        ru:'з',
        shiftRu:'З',
    },
    {
        id: 26,
        row: 2,
        place: 12,
        en:'[',
        shiftEn:'{',
        ru:'х',
        shiftRu:'Х',
    },
    {
        id: 27,
        row: 2,
        place: 13,
        en:']',
        shiftEn:'}',
        ru:'ъ',
        shiftRu:'Ъ',
    },
    {
        id: 28,
        row: 2,
        place: 14,
        en:'\\',
        shiftEn:'|',
        ru:'\\',
        shiftRu:'/',
    },
    {
        id: 29,
        row: 2,
        place: 15,
        en:'DEL',
        shiftEn:'DEL',
        ru:'DEL',
        shiftRu:'DEL',
    },
    {
        id: 30,
        row: 3,
        place: 1,
        en:'Caps Lock',
        shiftEn:'Caps Lock',
        ru:'Caps Lock',
        shiftRu:'Caps Lock',
    },
    {
        id: 31,
        row: 3,
        place: 2,
        en:'a',
        shiftEn:'A',
        ru:'ф',
        shiftRu:'Ф',
    },
    {
        id: 32,
        row: 3,
        place: 3,
        en:'s',
        shiftEn:'S',
        ru:'ы',
        shiftRu:'Ы',
    },
    {
        id: 33,
        row: 3,
        place: 4,
        en:'d',
        shiftEn:'D',
        ru:'в',
        shiftRu:'В',
    },
    {
        id: 34,
        row: 3,
        place: 5,
        en:'f',
        shiftEn:'F',
        ru:'а',
        shiftRu:'А',
    },
    {
        id: 35,
        row: 3,
        place: 6,
        en:'g',
        shiftEn:'G',
        ru:'п',
        shiftRu:'П',
    },
    {
        id: 36,
        row: 3,
        place: 7,
        en:'h',
        shiftEn:'H',
        ru:'р',
        shiftRu:'Р',
    },
    {
        id: 37,
        row: 3,
        place: 8,
        en:'j',
        shiftEn:'J',
        ru:'о',
        shiftRu:'О',
    },
    {
        id: 38,
        row: 3,
        place: 9,
        en:'k',
        shiftEn:'K',
        ru:'л',
        shiftRu:'Л',
    },
    {
        id: 39,
        row: 3,
        place: 10,
        en:'l',
        shiftEn:'L',
        ru:'д',
        shiftRu:'Д',
    },
    {
        id: 40,
        row: 3,
        place: 11,
        en:';',
        shiftEn:':',
        ru:'ж',
        shiftRu:'Ж',
    },
    {
        id: 41,
        row: 3,
        place: 12,
        en:"'",
        shiftEn:'"',
        ru:'э',
        shiftRu:'Э',
    },
    {
        id: 42,
        row: 3,
        place: 13,
        en:'ENTER',
        shiftEn:'ENTER',
        ru:'ENTER',
        shiftRu:'ENTER',
    },
    {
        id: 43,
        row: 4,
        place: 1,
        en:'Shift',
        shiftEn:'Shift',
        ru:'Shift',
        shiftRu:'Shift',
    },
    {
        id: 44,
        row: 4,
        place: 2,
        en:'z',
        shiftEn:'Z',
        ru:'я',
        shiftRu:'Я',
    },
    {
        id: 45,
        row: 4,
        place: 3,
        en:'x',
        shiftEn:'X',
        ru:'ч',
        shiftRu:'Ч',
    },
    {
        id: 46,
        row: 4,
        place: 4,
        en:'c',
        shiftEn:'C',
        ru:'с',
        shiftRu:'С',
    },
    {
        id: 47,
        row: 4,
        place: 5,
        en:'v',
        shiftEn:'V',
        ru:'м',
        shiftRu:'М',
    },
    {
        id: 48,
        row: 4,
        place: 6,
        en:'b',
        shiftEn:'B',
        ru:'и',
        shiftRu:'И',
    },
    {
        id: 49,
        row: 4,
        place: 7,
        en:'n',
        shiftEn:'N',
        ru:'т',
        shiftRu:'Т',
    },
    {
        id: 50,
        row: 4,
        place: 8,
        en:'m',
        shiftEn:'M',
        ru:'ь',
        shiftRu:'Ь',
    },
    {
        id: 51,
        row: 4,
        place: 9,
        en:',',
        shiftEn:'<',
        ru:'б',
        shiftRu:'Б',
    },
    {
        id: 52,
        row: 4,
        place: 10,
        en:'.',
        shiftEn:'>',
        ru:'ю',
        shiftRu:'Ю',
    },
    {
        id: 53,
        row: 4,
        place: 11,
        en:'/',
        shiftEn:'?',
        ru:'.',
        shiftRu:',',
    },
    {
        id: 54,
        row: 4,
        place: 12,
        en:'ArrUp',
        shiftEn:'ArrUp',
        ru:'ArrUp',
        shiftRu:'ArrUp',
    },
    {
        id: 55,
        row: 4,
        place: 13,
        en:'Shift',
        shiftEn:'Shift',
        ru:'Shift',
        shiftRu:'Shift',
    },
    {
        id: 56,
        row: 5,
        place: 1,
        en:'Ctrl',
        shiftEn:'Ctrl',
        ru:'Ctrl',
        shiftRu:'Ctrl',
    },
    {
        id: 57,
        row: 5,
        place: 2,
        en:'Win',
        shiftEn:'Win',
        ru:'Win',
        shiftRu:'Win',
    },
    {
        id: 58,
        row: 5,
        place: 3,
        en:'Alt',
        shiftEn:'Alt',
        ru:'Alt',
        shiftRu:'Alt',
    },
    {
        id: 59,
        row: 5,
        place: 4,
        en:'White space',
        shiftEn:'White space',
        ru:'White space',
        shiftRu:'White space',
    },
    {
        id: 60,
        row: 5,
        place: 5,
        en:'Alt',
        shiftEn:'Alt',
        ru:'Alt',
        shiftRu:'Alt',
    },
    {
        id: 61,
        row: 5,
        place: 6,
        en:'Ctrl',
        shiftEn:'Ctrl',
        ru:'Ctrl',
        shiftRu:'Ctrl',
    },
    {
        id: 62,
        row: 5,
        place: 7,
        en:'ArrLeft',
        shiftEn:'ArrLeft',
        ru:'ArrLeft',
        shiftRu:'ArrLeft',
    },
    {
        id: 63,
        row: 5,
        place: 8,
        en:'ArrDown',
        shiftEn:'ArrDown',
        ru:'ArrDown',
        shiftRu:'ArrDown',
    },
    {
        id: 64,
        row: 5,
        place: 9,
        en:'ArrRight',
        shiftEn:'ArrRight',
        ru:'ArrRight',
        shiftRu:'ArrRight',
    },
    

]

export default keyboard;